name: proyecto_modelos_1
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  cupertino_icons: ^1.0.2
  rflutter_alert: ^1.1.0
  shimmer: ^1.0.1
  audioplayers: ^0.15.1

  # Firebase
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.5
  firebase_admin: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/sounds/
